export interface MarketSeed {
  id: number;
  steamQuery: string;
}

export const MARKET_SEEDS: MarketSeed[] = [
  { id: 1, steamQuery: "Frostivus 2023 Treasure Chest" },
  { id: 2, steamQuery: "Dead Reckoning Chest" },
  { id: 3, steamQuery: "Spina Infernalis" },
  { id: 4, steamQuery: "Crownfall - Dire Creeps" },
  { id: 5, steamQuery: "Crownfall - Radiant Creeps" },
  { id: 6, steamQuery: "Immortal Treasure I 2022" },
  { id: 7, steamQuery: "Stoneclaw Scavengers Dire Towers" },
  { id: 8, steamQuery: "Stoneclaw Scavengers Radiant Towers" },
  { id: 9, steamQuery: "Mantle of the Whispered Bond" },
  { id: 10, steamQuery: "Magus Apex" },
  { id: 11, steamQuery: "Crux of Perplex" },
  { id: 12, steamQuery: "Arms of Desolation" },
  { id: 13, steamQuery: "Origins of Faith" },
  { id: 14, steamQuery: "The Devotions of Dragonus - Wings" },
  { id: 15, steamQuery: "Manifold Paradox" },
  { id: 16, steamQuery: "Demon Eater" },
  { id: 17, steamQuery: "Exalted Bladeform Legacy" },
  { id: 18, steamQuery: "Fractal Horns of Inner Abysm" },
  { id: 19, steamQuery: "Dark Artistry Cape" },
  { id: 20, steamQuery: "Dragonclaw Hook" },
  { id: 21, steamQuery: "Fiery Soul of the Slayer" },
  { id: 22, steamQuery: "Frost Avalanche" },
  { id: 23, steamQuery: "Provocation of Ruin" },
  { id: 24, steamQuery: "Feast of Abscession" },
  { id: 25, steamQuery: "Tempest Helm of the Thundergod" },
  { id: 26, steamQuery: "Sovereign of Torment" },
  { id: 27, steamQuery: "Compass of the Rising Gale" },
  { id: 28, steamQuery: "The Silent Wake" },
  { id: 29, steamQuery: "Claszureme Incursion" },
  { id: 30, steamQuery: "Ancient Inheritance" },
  { id: 31, steamQuery: "The One True King" },
  { id: 32, steamQuery: "Voidstorm Asylum" },
  { id: 33, steamQuery: "Phantom Advent" },
  { id: 34, steamQuery: "Flockheart's Gamble" },
  { id: 35, steamQuery: "Planetfall" },
  { id: 36, steamQuery: "Codicil of the Veiled Ones" },
  { id: 37, steamQuery: "Dark Artistry Bracers" },
  { id: 38, steamQuery: "Dark Artistry Hair" },
  { id: 39, steamQuery: "The Abscesserator" },
  { id: 40, steamQuery: "Scavenging Guttleslug" },
  { id: 41, steamQuery: "Blazing Cosmos" },
  { id: 42, steamQuery: "White Sentry" },
  { id: 43, steamQuery: "Golden Basher of Mage Skulls" },
  { id: 44, steamQuery: "Jagged Honor" },
  { id: 45, steamQuery: "Golden Arms of Desolation" },
  { id: 46, steamQuery: "Golden Staff of Perplex" },
  { id: 47, steamQuery: "Heavenly General" },
  { id: 48, steamQuery: "Bloodfeather Finery" },
  { id: 49, steamQuery: "Sylvan Vedette" },
  { id: 50, steamQuery: "Glacial Cascade" },
  { id: 51, steamQuery: "Mace of Aeons" },
  { id: 52, steamQuery: "Majesty of the Colossus" },
  { id: 53, steamQuery: "Golden Fractal Horns of Inner Abysm" },
  { id: 54, steamQuery: "Kindred of the Iron Dragon" },
  { id: 55, steamQuery: "Immortal Treasure II 2022" },
  { id: 56, steamQuery: "Immortal Treasure III 2022" },
  { id: 57, steamQuery: "Baby Roshan" },
  { id: 58, steamQuery: "Unusual Hollow Jack" },
  { id: 59, steamQuery: "Unusual Azuremir" },
  { id: 60, steamQuery: "Golden Scavenging Guttleslug" },
];
