export interface MarketSeed {
  id: number;
  steamQuery: string;
}

export const MARKET_SEEDS: MarketSeed[] = [
  { id: 1, steamQuery: "Frostivus 2023 Treasure Chest" },
  { id: 2, steamQuery: "Dead Reckoning Chest" },
  { id: 3, steamQuery: "Spina Infernalis" },
  { id: 4, steamQuery: "Crownfall - Dire Creeps" },
  { id: 5, steamQuery: "Crownfall - Radiant Creeps" },
  { id: 6, steamQuery: "Immortal Treasure I 2022" },
  { id: 7, steamQuery: "Stoneclaw Scavengers Dire Towers" },
  { id: 8, steamQuery: "Stoneclaw Scavengers Radiant Towers" },
  { id: 9, steamQuery: "Mantle of the Whispered Bond" },
  { id: 10, steamQuery: "Magus Apex" },
  { id: 11, steamQuery: "Crux of Perplex" },
  { id: 12, steamQuery: "Arms of Desolation" },
  { id: 13, steamQuery: "Origins of Faith" },
  { id: 14, steamQuery: "The Devotions of Dragonus - Wings" },
  { id: 15, steamQuery: "Manifold Paradox" },
  { id: 16, steamQuery: "Demon Eater" },
  { id: 17, steamQuery: "Exalted Bladeform Legacy" },
  { id: 18, steamQuery: "Fractal Horns of Inner Abysm" },
  { id: 19, steamQuery: "Dark Artistry Cape" },
  { id: 20, steamQuery: "Dragonclaw Hook" },
  { id: 21, steamQuery: "Fiery Soul of the Slayer" },
  { id: 22, steamQuery: "Frost Avalanche" },
  { id: 23, steamQuery: "Provocation of Ruin" },
  { id: 24, steamQuery: "Feast of Abscession" },
  { id: 25, steamQuery: "Tempest Helm of the Thundergod" },
  { id: 26, steamQuery: "Sovereign of Torment" },
  { id: 27, steamQuery: "Compass of the Rising Gale" },
  { id: 28, steamQuery: "The Silent Wake" },
  { id: 29, steamQuery: "Claszureme Incursion" },
  { id: 30, steamQuery: "Ancient Inheritance" },
  { id: 31, steamQuery: "The One True King" },
  { id: 32, steamQuery: "Voidstorm Asylum" },
  { id: 33, steamQuery: "Phantom Advent" },
  { id: 34, steamQuery: "Flockheart's Gamble" },
  { id: 35, steamQuery: "Planetfall" },
  { id: 36, steamQuery: "Codicil of the Veiled Ones" },
  { id: 37, steamQuery: "Dark Artistry Bracers" },
  { id: 38, steamQuery: "Dark Artistry Hair" },
  { id: 39, steamQuery: "The Abscesserator" },
  { id: 40, steamQuery: "Scavenging Guttleslug" },
  { id: 41, steamQuery: "Blazing Cosmos" },
  { id: 42, steamQuery: "White Sentry" },
  { id: 43, steamQuery: "Golden Basher of Mage Skulls" },
  { id: 44, steamQuery: "Jagged Honor" },
  { id: 45, steamQuery: "Golden Arms of Desolation" },
  { id: 46, steamQuery: "Golden Staff of Perplex" },
  { id: 47, steamQuery: "Heavenly General" },
  { id: 48, steamQuery: "Bloodfeather Finery" },
  { id: 49, steamQuery: "Sylvan Vedette" },
  { id: 50, steamQuery: "Glacial Cascade" },
  { id: 51, steamQuery: "Mace of Aeons" },
  { id: 52, steamQuery: "Majesty of the Colossus" },
  { id: 53, steamQuery: "Golden Fractal Horns of Inner Abysm" },
  { id: 54, steamQuery: "Kindred of the Iron Dragon" },
  { id: 55, steamQuery: "Immortal Treasure II 2022" },
  { id: 56, steamQuery: "Immortal Treasure III 2022" },
  { id: 57, steamQuery: "Baby Roshan" },
  { id: 58, steamQuery: "Unusual Hollow Jack" },
  { id: 59, steamQuery: "Unusual Azuremir" },
  { id: 60, steamQuery: "Golden Scavenging Guttleslug" },
  { id: 61, steamQuery: "Mantle of the Cinder Baron" },
  { id: 62, steamQuery: "Axe of Phractos" },
  { id: 63, steamQuery: "Muh Keen Gun" },
  { id: 64, steamQuery: "Full-Bore Bonanza" },
  { id: 65, steamQuery: "Sea Rake's Bridle" },
  { id: 66, steamQuery: "Shadow in the Deep" },
  { id: 67, steamQuery: "Staff of Gun-Yu" },
  { id: 68, steamQuery: "Golden Staff of Gun-Yu" },
  { id: 69, steamQuery: "Vigil Triumph" },
  { id: 70, steamQuery: "Storm Hammer" },
  { id: 71, steamQuery: "Spear of the Daemonfell Flame" },
  { id: 72, steamQuery: "Molten Bore" },
  { id: 73, steamQuery: "Golden Moonfall" },
  { id: 74, steamQuery: "Moonfall" },
  { id: 75, steamQuery: "Axia of Metira" },
  { id: 76, steamQuery: "Pulsar Remnant" },
  { id: 77, steamQuery: "The Lightning Orchid" },
  { id: 78, steamQuery: "Cinder Sensei" },
  { id: 79, steamQuery: "Hidden Vector" },
  { id: 80, steamQuery: "Focal Resonance" },
  { id: 81, steamQuery: "Hunter's Hoard" },
  { id: 82, steamQuery: "Blastforge Exhaler" },
  { id: 83, steamQuery: "Resistive Pinfold" },
  { id: 84, steamQuery: "Sullen Harvest" },
  { id: 85, steamQuery: "Golden Profane Union" },
  { id: 86, steamQuery: "Maraxiform's Ire" },
  { id: 87, steamQuery: "Whisky the Stout Artifact" },
  { id: 88, steamQuery: "Bonkers the Mad" },
  { id: 89, steamQuery: "World Chasm Artifact" },
  { id: 90, steamQuery: "Leviathan Whale Blade" },
];
